### ISSUE TITLE
error in console

### ISSUE THREAD

**Issue by Devillion** [CoolLord22/OtherDrops#78] opened 2019-07-13 04:02 UTC
**Describe the bug**
When I attack a mob this error shows up in the console and my script doesn't work https://pastebin.com/RgCx2MCN

**To Reproduce**
Attack a mob

**Expected behavior**
When the mob dies it runs my commands

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Java Version
https://i.imgur.com/ZJ6sFnH.png
 - Server Version 1.13.2
 - Plugin Version 1.13-3.2.6

my script
https://i.imgur.com/liLCTRz.png

**Comment by CoolLord22** [comment] 2019-07-13 10:28
Hi there! This hasn’t already been reported and has already been resolved in 3.2.7. As 3.2.7 is a beta build still, it’s not ready for release yet. However, if you would like the build, feel free to grab it from our discord server where beta updates are posted! Thank you for using GitHub, let us know if you have any questions/issues. Duplicate of #28

**Closed by CoolLord22** 2019-07-13 10:28 UTC
Labels: ⨂ Duplicate Issue
