### ISSUE TITLE
COMMAND: parameter.

### ISSUE THREAD

**Issue by WIDELEC-X** [CoolLord22/OtherDrops#88] opened 2019-10-01 14:17 UTC
After many tries I found out that basic command (example:/reload) are execute but commands with parameters (example: /time set day) not. Same about commands from other plugins - not executed.

SERVER V: SPIGOT MC 1.14.4
PLUGIN V: 3.2.7

**Comment by CoolLord22** [comment] 2019-10-01 18:13
Could you update this following the proper bug report format :) thank you!!

**Comment by WIDELEC-X** [comment] 2019-10-06 10:38
**Describe the bug**
After many tries I found out that basic command (example:/reload) are execute but commands with parameters (example: /time set day) not. Same about commands from other plugins - not executed.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'server'
2. Click on 'kill any mob with command added by otherdrops'
3. Scroll down to 'watch results'
4. See error 'command is not executed'

**Expected behavior**
Execute minecraft and other plugins commands.

**Screenshots**
Nothing happen.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Java Version [e.g. 8 build 171]
 - Server Version [e.g. Spigot 1.14.4]
 - Plugin Version [e.g. 3.2.7]

**Additional context**
If you fix this, THANK YOU MAN!

**Comment by CoolLord22** [comment] 2023-09-26 07:21
Duplicate of #91- vanilla commands cannot be executed by console for some reason.

**Closed by CoolLord22** 2023-09-26 07:21 UTC
Labels: 🔍 Investigating, Build - 1.13
