### ISSUE TITLE
ERROR Could not pass event EntityDamageEvent to OtherDrops_1.13 v3.2.6

### ISSUE THREAD

**Issue by IITFA** [CoolLord22/OtherDrops#65] opened 2019-05-09 03:37 UTC
EDIT: This seems to be fixed in the beta version found on Discord.

**Describe the bug**
Just installed, copied over the part from random examples include about dropping glowstone dust when mining redstone with a golden pick. Reloaded. Tried to mine redstone ore with a gold pick, nothing drops, error in console.

I have yet to test anything else, but tried mining redstone ore with gold pick and the redstone drops nothing and there's an error in the console.

**To Reproduce**
1: Copy over the part of random examples about mining redstone with a gold pick to get glowstone dust.
2: Reload
3: Try to mine redstone ore with gold pick

**Expected behavior**
Expected to get glowstone dust

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10] MX Linux
 - Java Version [e.g. 8 build 171] Not sure
 - Server Version [e.g. Spigot 1.12] PPaper version git-Paper-622 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
 - Plugin Version [e.g. 3.2.6 Legacy/1.13] OtherDrops_1.13 v3.2.6

**Additional context**
Totally new to the plugin, haven't even tried to make it drop what I want to drop. Using basically the config that came with it.

Error:
https://hastebin.com/ixawohayah.apache

**Comment by CoolLord22** [comment] 2019-05-09 09:19
As you’ve found, it’s resolved in the beta :)

Marking as Duplicate of #28.

**Closed by CoolLord22** 2019-05-09 09:19 UTC
