### ISSUE TITLE
Otherdrops doesn't work with WorldGuard

### ISSUE THREAD

**Issue by nexopl** [CoolLord22/OtherDrops#69] opened 2019-05-29 21:01 UTC
**Describe the bug**
When i delete Worldguard from the server otherdrops works perfect but if i add worldguard it doenst work

[Server thread/ERROR]: Could not pass event BlockBreakEvent to OtherDrops v3.2.6
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[mc.jar:git-Bukkit-cb3d14c]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[mc.jar:git-Bukkit-cb3d14c]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:519) ~[mc.jar:git-Bukkit-cb3d14c]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:504) ~[mc.jar:git-Bukkit-cb3d14c]
at net.minecraft.server.v1_14_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286) ~[mc.jar:git-Bukkit-cb3d14c]
at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:219) ~[mc.jar:git-Bukkit-cb3d14c]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1188) ~[mc.jar:git-Bukkit-cb3d14c]
at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[mc.jar:git-Bukkit-cb3d14c]
at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[mc.jar:git-Bukkit-cb3d14c]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[mc.jar:git-Bukkit-cb3d14c]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [mc.jar:git-Bukkit-cb3d14c]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [mc.jar:git-Bukkit-cb3d14c]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [mc.jar:git-Bukkit-cb3d14c]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [mc.jar:git-Bukkit-cb3d14c]
at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:853) [mc.jar:git-Bukkit-cb3d14c]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:846) [mc.jar:git-Bukkit-cb3d14c]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [mc.jar:git-Bukkit-cb3d14c]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:830) [mc.jar:git-Bukkit-cb3d14c]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:770) [mc.jar:git-Bukkit-cb3d14c]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionContainer()Lcom/sk89q/worldguard/bukkit/RegionContainer;
at com.gmail.zariust.otherdrops.event.OccurredEvent.setRegions(OccurredEvent.java:803) ~[?:?]
at com.gmail.zariust.otherdrops.event.OccurredEvent.<init>(OccurredEvent.java:130) ~[?:?]
at com.gmail.zariust.otherdrops.listener.OdBlockListener.onBlockBreak(OdBlockListener.java:106) ~[?:?]
at sun.reflect.GeneratedMethodAccessor245.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[mc.jar:git-Bukkit-cb3d14c]

**Comment by CoolLord22** [comment] 2019-05-29 21:05
Hi there! This hasn’t already been reported (5 times alone on the github) and has already been resolved in 3.2.7. As 3.2.7 is a beta build still, it’s not ready for release yet. However, if you would like the build, feel free to grab it from our discord server where beta updates are posted! Thank you for using GitHub, let us know if you have any questions/issues. Duplicate of #28

**Closed by CoolLord22** 2019-05-29 21:05 UTC
Labels: ⨂ Duplicate Issue
