### ISSUE TITLE
Enchantments can't be used for ANY/ALL tool option.

### ISSUE THREAD

**Issue by GrandeMalum** [CoolLord22/OtherDrops#22] opened 2018-07-25 11:21 UTC
**Describe the bug**
**_Well, for some reason plugin not recognizes enchantments for ANY or ALL tool option. There is no errors or anything alike in console. The drop can be triggered by any item, even without needed enchantment._**

**_By the way, this is my testing drops file:_**
    _ZOMBIE:
        - drop: IRON_INGOT
          trigger: BREAK
          tool: ANY_SWORD@!LOOTING#1
          chance: 100.0
        - drop: EMERALD
          trigger: BREAK
          tool: ANY_SWORD@!LOOTING#2
          chance: 100.0
        - drop: DIAMOND
          trigger: BREAK
          tool: ANY_SWORD@!LOOTING#3
          chance: 100.0_

_**And that's my configuration file:**_
_https://pastebin.com/ztCgXck9_

**Expected behavior**
_**I was expecting that I could use any item with "Looting I" enchantment to trigger the drop.**_

**Screenshots**
_**I don't think that screenshots are needed here.**_

**Desktop (please complete the following information):**
 _**- OS: Not sure about windows, cause I'm using a host machine.
 - Java Version: 8 build 171.
 - Server Version: Spigot 1.12.
 - Plugin Version: 3.2.6.**_

**Additional context**
**_I hope that the plugin would be fixed as soon as possible. Thanks._**

**Comment by CoolLord22** [comment] 2018-07-26 14:10
The issue is with the `!` When you use `ANY_SWORD@!LOOTING#3` the plugin makes the enchantment equal to `!LOOTING` which is not an enchant. Try removing the `!` and let me know the results. The `!` should (generally) be used as a separator for different specifications.

**Comment by Zomblad** [comment] 2018-07-26 14:43
Removed it, but still I have the same issue.

**Comment by CoolLord22** [comment] 2018-07-26 14:48
I understand, what ANY_SWORD would do is allow any sword to trigger the drop (I believe). The only way around it is to manually add the sword in.

**Comment by CoolLord22** [comment] 2018-08-11 12:48
This has never been supported, and in all honesty, I can't think of a way to implement this into the plugin, so, unfortunately, I am closing for now. If, sometime in the future, I can figure out a way to add this in, we'll reopen :)

**Comment by CoolLord22** [comment] 2019-05-11 14:23
Reopening this as I’ve gotten better at programming so it might be possible in the future ;)

**Comment by antolo-arch** [comment] 2019-09-29 09:13
I have a simmilar issue, it doesn't recognize more than one enchant on a pickaxe
drop: DIAMOND
          tool: diamond_pickaxe@efficiency#4!fortune#3!unbreaking#3
          chance: 100%
          quantity: 1-3
          height: <25
is there anyting wrong in the code?

**Comment by CoolLord22** [comment] 2019-09-29 13:39
@antolo-arch Please open a new issue. This one is only for the ALL tool option so it isn’t the same. As a side note, please be sure to explain more about what you mean; does it not require all the enchants? Or is it not letting any pickaxe with other enchants drop it?

**Comment by CoolLord22** [comment] 2023-09-26 06:45
Closing as I'm realizing this is plugin design; the ANY modifier is meant to allow quite literally ANY variant to trigger the drop, regardless of what enchant/name/lore is on it. To achieve this, simply add each variant with your customizations.

**Closed by CoolLord22** 2023-09-26 06:45 UTC
Labels: ＋ Enhancement, ⨂ Won't Fix, Both Builds
