### ISSUE TITLE
Could not pass event BlockBreakEvent to OtherDrops_1.13 v3.2.6 using minecraft 1.13.1

### ISSUE THREAD

**Issue by arturek1666** [CoolLord22/OtherDrops#31] opened 2018-09-07 16:19 UTC
**Describe the bug**
Massive error:
```
[K[31;1m[18:12:29 ERROR]: Could not pass event BlockBreakEvent to OtherDrops_1.13 v3.2.6
java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionContainer()Lcom/sk89q/worldguard/bukkit/RegionContainer;
        at com.gmail.zariust.otherdrops.event.OccurredEvent.setRegions(OccurredEvent.java:803) ~[?:?]
        at com.gmail.zariust.otherdrops.event.OccurredEvent.<init>(OccurredEvent.java:130) ~[?:?]
        at com.gmail.zariust.otherdrops.listener.OdBlockListener.onBlockBreak(OdBlockListener.java:106) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor494.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.1.jar:git-Paper-224]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.1.jar:git-Paper-224]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.1.jar:git-Paper-224]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.13.1.jar:git-Paper-224]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.13.1.jar:git-Paper-224]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:299) ~[patched_1.13.1.jar:git-Paper-224]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:225) ~[patched_1.13.1.jar:git-Paper-224]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1271) ~[patched_1.13.1.jar:git-Paper-224]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.13.1.jar:git-Paper-224]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.13.1.jar:git-Paper-224]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.1.jar:git-Paper-224]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_144]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) ~[patched_1.13.1.jar:git-Paper-224]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.1.jar:git-Paper-224]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:428) ~[patched_1.13.1.jar:git-Paper-224]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:936) ~[patched_1.13.1.jar:git-Paper-224]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:834) ~[patched_1.13.1.jar:git-Paper-224]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144][39;0m
```

**To Reproduce**
Please use newest 1.13.1 and install the plugin. After that add some stuff to config and try to mine that block it will show the error.

**Expected behavior**
Plugin don't work :( everytime i mine a stone it will come up with this error in console

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Java Version java 8
 - Server Version PaperSpigot 1.13.1
 - Plugin Version: v3.2.6

**Comment by CoolLord22** [comment] 2018-09-08 18:09
Duplicate of #28

**Closed by CoolLord22** 2018-09-08 18:09 UTC
Labels: Duplicate
